### ISSUE TITLE
Generalization of RenameGenesSeurat for other data types and slots

### ISSUE THREAD

**Issue by seb-mueller** [vertesy/Seurat.utils#61]
**Description**
Moving discussion of [this PR](https://github.com/vertesy/Seurat.utils/pull/59) to issue to be able to track it better accross PRs.

I'm about to fix the introduced bugs in above PR, but have a some info as well as a question.
As a follow up, I've asked a question about data types in a seurat object [here](https://github.com/satijalab/seurat/issues/7193): turns out data types can be anything, so we need to check since it might be i.e. `dgeCMatrix` of `Matrix`.

1. One way which works for both classes, would be to use `rownames(obj)` instead of `obj@Dimnames[[1]]`. I was wondering why `Dimnames` were used in the first place, just trying to work out if `rownames` is fine to use instead.

2. A general question: we assume the 3 slots have the same number/order of genes, however I found that `@scale.data` can have less genes, i.e. in the shipped `small_pbmc` object, there are only 20 instead of 230 as in `@data`. If was wondering how this function dealt with this in the past, am I missing something? 
 
```r
library(seurat)
> dim(pbmc_small@assays[["RNA"]]@scale.data)
[1] 20 80
> dim(pbmc_small@assays[["RNA"]]@data)
[1] 230  80
> dim(pbmc_small@assays[["RNA"]]@counts)
[1] 230  80
```

**Comment by vertesy** [comment]
Hey,


on 1): not specific reason that I can recall now, but I wonder if this change to rownames would not break sth else - the two calls seem rather different.

2) There should be no gene filtering done for Scaledata. This is the basis for PCA, so I guess you can take variable genes? I never subset, sounds like a dangerous practice. 
I see that `ScaleData(...,  features = )` can be provided with gene list.

I think there is no easy solution. The current code should break when unequal, so that's good.
 My preferred solution would be to

```r
if (also.ScaleData)  { if (length(assayobj@scale.data) > 0) assayobj@scale.data@Dimnames[[1]] <- newnames }
```
where `ScaleData = TRUE` is an argument -> This way it tries by default, but you can actively turn it off.

**Comment by seb-mueller** [comment]
Thanks for the feedback, I agree and tried to incorperate your suggestions. I haven't thourgouly tested, but wanted to get your general opinion if this is what you had in mind. Should be more generic now, I'll do some testing once I find more time.
