### ISSUE TITLE
UpdateGenesSeurat results in Error in .make_numeric_version(x, strict, ....

### ISSUE THREAD

**Issue by KGSchilling** [vertesy/Seurat.utils#75]
**Description**
...Using function UpdateGenesSeurat from package Seurat.utils,  I get the following error message:

```r
  Error in .make_numeric_version(x, strict,
  .standard_regexps()$valid_numeric_version) :
   invalid non-character version specification 'x' (type: double)
```

I am not sure whether this is a bug and if so, where?), or reflects my  ignorance. However, I suspect that this may relate to the R version I  use (R 4.4. under windows 10), as might be suggested by the discussion
   at https://stat.ethz.ch/pipermail/r-devel/2023-July/082722.html
    <https://stat.ethz.ch/pipermail/r-devel/2023-July/082722.html>.

The problem is not due to my dataset, as it is reproducible with the pbmc3k data.
All packages installed are up-to date (as of May 23, 2024).

It has been suggested to me that the error relates to the internal Seurat.utils:::.make_numeric_version() function.

Is there a work around, or could this be fixed?

Thank you so much the internal Seurat.utils:::.make_numeric_version() function.
Best

Karl Schilling

**Expected Behavior**
...

**Buggy Behavior**
...

```r
data("pbmc3k")

pbmc3k@images <- list()

updatedPbmc3k <- UpdateGenesSeurat(
  obj = pbmc3k,
  species = "human",
  EnforceUnique = TRUE,
  ShowStats = "TRUE"
)


```

**Comment by vertesy** [comment]
Hey Karl,

thanks for reporting. I use R 4.3. Not tested on 4.4.

On my R version and object it completes correctly.

I think there is no ` Seurat.utils:::.make_numeric_version()` so I am not sure what you are referring to.

The link to `r-devel` seems to be a very helpful to find this bug.

I think maybe somewhere an `as.numeric()` is used.  I quickly searched but did not find.

Probably the default should be changed as suggested in `r-devel`. 

`Seurat.utils` uses my functions in `CodeAndroll2`, it has the likes of `as.numeric.wNames.character()`. 
Probably the problem is there.


Bc, I don't plan to switch to 4.4 this is beyond my energy to troubleshoot. Sorry for that.

**Comment by KGSchilling** [comment]
Dear Abel,

thank you for clarifying response. Seems I got caught in the winds of change ...

Karl

**Comment by jpsmith5** [comment]
Sorry for commenting on closed issue here, but this error appears to stem from checks of `if (obj@version < 5)`.  If this is instead changed to `if (obj@version < "5")` the error is resolved.

See:
 - https://github.com/vertesy/Seurat.utils/blob/d3dcbde4793ab096b645dd25363897900b1ccad6/R/Seurat.Utils.R#L5497
 - https://github.com/vertesy/Seurat.utils/blob/d3dcbde4793ab096b645dd25363897900b1ccad6/R/Seurat.Utils.R#L3807
 - https://github.com/vertesy/Seurat.utils/blob/d3dcbde4793ab096b645dd25363897900b1ccad6/R/Seurat.Utils.R#L520 

This is on:
```
R version 4.4.1 (2024-06-14)
Seurat.utils_2.8.0
```

**Comment by vertesy** [comment]
Hey, thanks for your suggestion.


1. for me it works assuming its numeric
```r
> obj@version
[1] ‘5.0.2’

> (obj@version)<6
[1] TRUE
> (obj@version)>6
[1] FALSE

### And your way works too
> (obj@version)<"6"
[1] TRUE
> (obj@version)>"6"
[1] FALSE
```

2.  Interestingly, however, it is not numeric, and it even kind of be converted to
```r
> is(obj@version)
[1] "package_version" "oldClass"       

> as.numeric(obj@version)
Error: 'list' object cannot be coerced to type 'double'
```

Since 
- both are working for me, and
-  I am not really sure how exactly `x large than character_string` should works,
I would keep as is for now.

**Comment by vertesy** [comment]
Ahh... I am sorry I am locked into R.4.3.2.
Thank you!
Sorry for not having the energy to fix it.
I will update tonight.

Do u think that `as.numeric(substr(obj@version, 1,3))` would work instead character? Thank you!

**Comment by vertesy** [comment]
Ok I went for the "" solution as proposed.

**Comment by KGSchilling** [comment]
Dear Abel,

thank you so much. Just tested it with R4.4.1 - works like a charm
Just a hint: Other than Seurat.utils, I had to reinstall CodeAndRoll2 - otherwise installation of the updated Seurat.utils failed ( the lazy loading step.

Thank you again,

Karl
